### ISSUE TITLE
Etnaviv rebase against upstream mesa

### ISSUE THREAD

**Issue by tgorochowik** [laanwj/mesa#3]
Hey, I have rebased etnaviv driver against upsteam mesa and I'm dropping a line here to let you know about that:
https://github.com/tgorochowik/mesa

**Comment by laanwj** [comment]
Thanks! Did you run into issues?

**Comment by tgorochowik** [comment]
Mesa API has changed in several places, shader linker verification was also failing because of some new parameter, but afterall everything seems to work fine.

**Comment by laanwj** [comment]
I pushed your branch to the repositories, thanks!

**Comment by austriancoder** [comment]
You pushed it to https://github.com/etnaviv/mesa too? That makes it very hard to merge my fork back as I am doing lot of code changes to support libdrm-etnavvi and in the end kick the usage of physical gpu address in the mesa driver.

**Comment by laanwj** [comment]
@austriancoder Yes, but I moved the old branch to "pre_rebase_2014_09", so nothing is lost.
